[package]
name = "hotpath-drain-meta"
version = "0.0.2"
edition = "2021"
repository = "https://github.com/pawurb/hotpath-rs"
description = "Hotpath drain meta - a version of hotpath-drain used to profile the profiler itself. Not intended for external use."
readme = "README.md"
license = "MIT"
categories = ["concurrency", "data-structures"]

[dependencies]
