apiVersion: 1

datasources:
  - name: Prometheus
    uid: hotpath-prom
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Prometheus Legacy
    uid: hotpath-prom-legacy
    type: prometheus
    access: proxy
    url: http://prometheus-legacy:9090
    isDefault: false
  - name: Prometheus Meta
    uid: hotpath-prom-meta
    type: prometheus
    access: proxy
    url: http://prometheus-meta:9090
    isDefault: false
  - name: Prometheus Legacy Meta
    uid: hotpath-prom-legacy-meta
    type: prometheus
    access: proxy
    url: http://prometheus-legacy-meta:9090
    isDefault: false
