[book]
authors = ["pawurb"]
language = "en"
src = "src"
title = "hotpath-rs"

[build]
build-dir = "book"

[output.html]
site-url = "/"
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["src/custom.css", "theme/hotpath-nav.css"]
additional-js = ["src/custom.js"]
edit-url-template = "https://github.com/pawurb/hotpath-rs/edit/main/docs/{path}"

[output.html.print]
enable = false

[output.html.playground]
runnable = false

[preprocessor.assets-hash]

[preprocessor.reading-time]
